# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Pagespeed
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: pagespeed.svg
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          config_timezone: Asia/Yekaterinburg
          user: neandreev
          template: classic

          base: ''
          plugin_pagespeed: yes
          plugin_pagespeed_url: https://free-talk-next-js.vercel.app/
